version: "3.8"

services:
    web:
        build: .
        command: > 
            sh -c "python manage.py migrate && 
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/code
        ports:
            - 8000:8000
    
    celery:
        build: .
        command: celery -A MQ worker --loglevel=INFO
        volumes:
            - .:/code
        depends_on: 
            - redis
        
    redis:
        image: redis:6.2-alpine
        depends_on: 
            - web
    
    flower:
        image: mher/flower
        environment: 
            - CELERY_BROKER_URL=redis://redis:6379/0
            - FLOWER_PORT=5555
        ports:
            - 5555:5555
        depends_on: 
            - celery
